/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "elevator.v:6" *)
module elevator_yosys(CLK, Go_Up, Go_Down, Halt, Top_Limit_Hit, Bottom_Limit_Hit, state);
  wire [4:0] _00_;
  wire _01_;
  wire [4:0] _02_;
  wire [4:0] _03_;
  wire _04_;
  wire [4:0] _05_;
  wire [4:0] _06_;
  wire _07_;
  wire [4:0] _08_;
  wire [4:0] _09_;
  wire _10_;
  wire [4:0] _11_;
  wire _12_;
  (* src = "elevator.v:12" *)
  input Bottom_Limit_Hit;
  (* src = "elevator.v:7" *)
  input CLK;
  (* src = "elevator.v:9" *)
  input Go_Down;
  (* src = "elevator.v:8" *)
  input Go_Up;
  (* src = "elevator.v:10" *)
  input Halt;
  (* src = "elevator.v:11" *)
  input Top_Limit_Hit;
  (* src = "elevator.v:15" *)
  wire [4:0] next;
  (* src = "elevator.v:13" *)
  output [4:0] state;
  reg [4:0] state;
  always @(posedge CLK)
      state <= next;
  assign _00_ = Go_Down ? (* src = "elevator.v:45" *) 5'b00100 : 5'b01000;
  assign _01_ = state == (* src = "elevator.v:28" *) 5'b01000;
  assign _02_ = Halt ? (* src = "elevator.v:41" *) 5'b00001 : 5'b00100;
  assign _03_ = Bottom_Limit_Hit ? (* src = "elevator.v:40" *) 5'b10000 : _02_;
  assign _04_ = state == (* src = "elevator.v:28" *) 5'b00100;
  assign _05_ = Halt ? (* src = "elevator.v:36" *) 5'b00001 : 5'b00010;
  assign _06_ = Top_Limit_Hit ? (* src = "elevator.v:35" *) 5'b01000 : _05_;
  assign _07_ = state == (* src = "elevator.v:28" *) 5'b00010;
  assign _08_ = Go_Down ? (* src = "elevator.v:31" *) 5'b00100 : 5'b00001;
  assign _09_ = Go_Up ? (* src = "elevator.v:30" *) 5'b00010 : _08_;
  assign _10_ = state == (* src = "elevator.v:28" *) 5'b00001;
  assign _11_ = Go_Up ? (* src = "elevator.v:49" *) 5'b00010 : 5'b10000;
  function [4:0] _26_;
    input [4:0] a;
    input [24:0] b;
    input [4:0] s;
    (* src = "elevator.v:28" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _26_ = b[4:0];
      5'b???1?:
        _26_ = b[9:5];
      5'b??1??:
        _26_ = b[14:10];
      5'b?1???:
        _26_ = b[19:15];
      5'b1????:
        _26_ = b[24:20];
      default:
        _26_ = a;
    endcase
  endfunction
  assign next = _26_(5'b00001, { _09_, _06_, _03_, _00_, _11_ }, { _10_, _07_, _04_, _01_, _12_ });
  assign _12_ = state == (* src = "elevator.v:28" *) 5'b10000;
endmodule
